# Generated by Django 5.1.1 on 2024-09-23 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='confirmada', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField()),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunas.cita')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('raza', models.CharField(max_length=45)),
                ('fecha_nacimiento', models.DateField()),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='vacunas.especie')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunas.propietario')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunas.mascota'),
        ),
        migrations.CreateModel(
            name='HistorialVacunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('administrada', 'Administrada'), ('no administrada', 'No Administrada')], max_length=20)),
                ('historial_medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunas.historialmedico')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacunas.vacuna')),
            ],
        ),
        migrations.AddField(
            model_name='cita',
            name='veterinario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vacunas.veterinario'),
        ),
    ]
