# Generated by Django 5.1.1 on 2024-09-23 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacunas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='estado',
        ),
        migrations.AlterField(
            model_name='historialmedico',
            name='cita',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vacunas.cita'),
        ),
        migrations.AlterField(
            model_name='historialmedico',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='historialvacunas',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('administrada', 'Administrada'), ('no administrada', 'No administrada')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='direccion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='email',
            field=models.EmailField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='email',
            field=models.EmailField(blank=True, max_length=45),
        ),
        migrations.AlterField(
            model_name='veterinario',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
